### ISSUE TITLE
Does 0 always stand for positive example after using StringIndexer ? 

### ISSUE THREAD

**Issue by chuqidecha** [ispras/pu4spark#3]
In every iterator, you use StringIndexer to rebuild label index and call method of getPOne to get positive sample probability. But, 0 always stands for the  most frequent label after StringIndexer  . Maybe I misunderstand somewhere?

**Comment by astrakhantsev** [comment]
Many thanks for noticing! Yes, it is indeed a bug. It was unnoticed previously due to the nature of positive-unlabeled learning, namely the fact that usually there are more negative than positive instances, but no doubt that we can't rely on this.
I fixed the bug (by using this [related question](https://stackoverflow.com/questions/35922214/how-to-make-binary-classication-in-spark-ml-without-stringindexer?rq=1) on stackoverflow).
